DROP TABLE IF EXISTS TBL_EMPLOYEES;
#DROP TABLE IF EXISTS UNIF_LOG_HIS_MGNT;
  
CREATE TABLE TBL_EMPLOYEES (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE UNIF_LOG_HIS_MGNT
(
	ULHM_ID 			CHAR(14),
	ULHM_HSEQ_NO 			INT,
	ULHM_SEVR_CAT 			VARCHAR(3),
	ULHM_SEVR_SRCH_NO 		VARCHAR(100),
	ULHM_ORG_CD			VARCHAR(8),
	ULHM_EMP_NO			VARCHAR(8),
	ULHM_SYS_LCLS_CD		VARCHAR(2),
	ULHM_SYS_MCLS_CD		VARCHAR(4),
	ULHM_SYS_FRM_CD		VARCHAR(10),
	ULHM_FRM_DECL_NM		VARCHAR(100),
	ULHM_BZ_OCCR_DT		CHAR(8),
	ULHM_PTSV_PERI_ED_DT		CHAR(8),
	ULHM_SEVR_FILE_NM		VARCHAR(500),
	ULHM_SEVR_PATH_NM		VARCHAR(3000),
	ULHM_USR_SECRT_GRD		VARCHAR(2),
	ULHM_ID_ADDR			VARCHAR(30),
	ULHM_REG_RESO_CNTS		VARCHAR(4000),
	ULHM_SCC_YN			CHAR(1),
	ULHM_VF_DT			DATE,
	ULHM_VT_DT			DATE,
	ULHM_DATA_OCCR_TS		TIMESTAMP,
	ULHM_ENTRY_EMP_NO		VARCHAR(8)
);